// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxHN4zqIxmVNj7cxSKUKxq5Yxgsz60X5Q',
    appId: '1:573584464318:web:7880dd7904864b5483c1ef',
    messagingSenderId: '573584464318',
    projectId: 'yukparkir-ead06',
    authDomain: 'yukparkir-ead06.firebaseapp.com',
    storageBucket: 'yukparkir-ead06.firebasestorage.app',
    measurementId: 'G-H8F4PSH2VX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0PYbi3vgWnqZzQhhOJi0Go2n2dT8cpNA',
    appId: '1:573584464318:android:5004ae9d9385d2eb83c1ef',
    messagingSenderId: '573584464318',
    projectId: 'yukparkir-ead06',
    storageBucket: 'yukparkir-ead06.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOo152e1x_2zjO6mYN8BsZLGYktvOBOAM',
    appId: '1:573584464318:ios:296a01a690034ac083c1ef',
    messagingSenderId: '573584464318',
    projectId: 'yukparkir-ead06',
    storageBucket: 'yukparkir-ead06.firebasestorage.app',
    iosBundleId: 'com.example.parkirYukk',
  );

}